#!/bin/ash
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
# Adds More APKs
#

#
apk add && \
    easy_install \
    emacs \
    emacs-nox \
    ethtool \
    file \
    fish \
    fish-dev \
    fortify-headers \
    g++ \
    gcc \
    gdbm \
    git \
    git-perl \
    glib \
    gmp \
    gmp-dev \
    gnutls \
    go \
    grep \
    hostapd \
    http-parser \
    hwdata-pci \
    isl \
    iw \
    libatomic \
    libblkid \
    libbz2 \
    libc-dev \
    libc-utils \
    libcap \
    libcrypto1.1 \
    libcurl --allow-untrusted && \
sh Add-Apks3
