#!/bin/ash

# License: GNU public
# Creator: Project Zero Days
# Github:  https://Github.com/ProjectZeroDays
# Website: https://ProjectZeroDays.com
# Email:   Info@ProjectZeroDays.com
# Secure:  ProjectZeroDays@pm.me
# Twitter: @ProjectZeroDays
# Reddit:  @ProjectZeroDays
# DEV:     @ProjectZeroDays 

# This script allows iSH testers to install iSH choosing package managers, develpment tools, pentesting tools, & configurations 
# to add to their iSH (re)installation & configuration. You choose whether to auto configure & install python3, Pip, Pipx, 
# Bkpg, Pacman, PipEnv, SSH, VNC, Ruby, etc., or to add our custom configurations such as our aliases added to the sys & to 
# /etc/profile, the ability to run daemons to allow iSH to take SSH/VNC connections even when the app is not running. You 
# Choose!

# Need to add files for BKPG and  add package manager folder to repo
# Use Pacman repo to add .sh for installing packages through pacman delete other files 
# Add Aliases to profile
# Add repositories file to SYS and add it to be swapped out
# add daemon in the background code 
# add easyinstall after pip
# confirm virtenv and add after pip
# bkpg to this and update printf when adding packages
# printf "/etc/passwd for -> iSH-Auto-Config/SYS/passwd\n'
# Add Config File For Neofetch 
# add printf "/etc/.ssh/sshd_config for -> iSH-Auto-Config/SYS/sshd_config\n' after SSH setu
# Install Pips
# Install Ruby Gems creat install file
# Install Python Programs
# Install Bkpg Programs
# Renanme and Relate Py3 Folder to .Py3

# Adding Necessary APKs to Run Script
apk add &&
    bash \
    wget \
    neofetch \
    git \
    lua \
    cmake \
    curl \
    docker \
    archivemount \
    autoconf \
    clang \
    cython \
    db --allow-untrusted && \
clear && \

# Cloning Repo
git clone https://github.com/projectzerodays/iSH-Auto-Config.git && \

# Changing Directory to iSH-Auto-config
cd iSH-Auto-Config && \

# Making SETUP Script Executable
chmod +x SETUP && \

# Run Config Script
sh SETUP
