#!/bin/bash
#
# Author:  Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
# 
PS1='root@kali:# ' && \
printf "Adding Necessary APKs & Configuring iSH \n" && \
apk add git curl wget neofetch python python3 && \
clear && \
mv SYS/passwd SYS/sshd_config SYS/profile SYS/motd /etc && \
chmod +x /SYS/Make-Exec && \
clear && \
sh /SYS/Make-Exec
