#!bin/bash
# Creator: Project Zero Days
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Email:   info@ProjectZeroDays.com, 
# Secure:  ProjectZeroDays@pm.me
alias kali="PS1="root@kali:# "
alias cheat="sh /usr/local/bin/cht"
alias autoremove="cache"
printf="Installs "Other Tools" which include an auto-updates, 
a desktop enviornment and Periphials 
(experimental use only - not fully working)."
#
# Installs Cheat Cheat (cht.sh) 
curl https://cht.sh/:cht.sh | tee /usr/local/bin/cht.sh && 
chmod +x /usr/local/bin/cht.sh && 
cht.sh --mode auto && 
mv /usr/local/bin/cht.sh /usr/local/bin/cht 
#
cd  
apk add && \
    apk-autoupdate \
    apk-autoupdate-doc \
    automake \
    automake-doc \
    autossh \
    autossh-doc \
    kmousetool \
    kmousetool-doc \
    mousepad \
    mousepad-doc \
    ghostscript \
    ghostscript-doc \
    libevdev \
    linphone \
    linphone-doc \
    xfce4-dev-tools \
    xfce4-settings \
    xf86-input-mouse \
    xf86-input-mouse-dev \
    zfs-auto-snapshot \
    zfs-auto-snapshot-doc \
bash 
cd ~/ 
clear
start 
kali  
 

