#!/bin/bash
apk add bash 
printf "Adding aliases to Alpine, if you are already running Ubuntu in iSH, use the other script instead of this one.\n"
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
#
alias kali=PS1="root@kali:# "
alias cheat="sh /usr/local/bin/cht"
alias startkali="neofetch --ascii_distro kali"
alias startubuntu="neofetch --ascii_distro ubuntu"
alias msfconsole="/usr/local/bin/msf"
#
clear
startkali
sh Add-Sources
