#!/bin/bash
#
# Author:  Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
#
PS1='root@kali:# ' && \
printf "Making Config Scripts Executable \n" && \
#
chmod +x Add-Sources && \
    SYS/Add-Aliases \
    Apk/Add-Apks \
    Apk/Add-Apks2 \
    Apk/Add-Apks3 \
    Apk/Add-Apks4 \
    Apk/Add-Apks5 \
    Apk/Add-Apks6 \
    Pip/Pip-Pipx-Pipenv-Config \
    Pip/Add-Pips \
    Tools/Add-Pentesting-Tools \
    Tools/Other-Tools \
    SYS/Setup-SSH \
    Apk/Add-Py3-Apks \
    VNC/Setup-x11vnc-Server \
    Ubuntu/Ubuntu-Rootfs_19.1_i386 && \
clear && \
sh SYS/Add-Sources
