#!/bin/bash
#
# Author:  Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
#
PS1='root@kali:# ' && \
printf "Configuring SSH for your system... \n" && \
#
apk add openssh openssh-client && \
ssh-keygen -A && \
passwd && \
clear && \
#
printf "This copies the updated configuration \n" && \
cp -L -f SYS/sshd_config /etc/ssh/sshd_config && \
echo Complete! && \
clear && \
sh VNC/Setup-x11vnc-Sever
