#!/bin/bash
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me

# Adds More APKs
apk update && \
apk upgrade && \
apk add && 
    alpine-baselayout \
    alpine-keys \
    apk-tools \
    apr \
    apr-util \
    argon2-libs \
    atools \
    archivemount \
    autoconf \
    binutils \
    bison \
    build-base \
    c-ares \
    ca-certificates \
    ca-certificates-cacert \
    clang \
    cmake \
    curl \
    cython \
    daq-sfbpf \
    db --allow-untrusted && 
clear && \

# Running APK3 Script
sh APK3

