#!/bin/bash 
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me

# Adding More APKs
apk add &&
    python3 \
    python3-dev \
    readline \
    readline-dev \
    rlwrap \
    ruby \
    ruby-bigdecimal \
    ruby-bundler \
    ruby-dev \
    ruby-etc \
    ruby-io-console \
    ruby-libs \
    scanelf \
    serf \
    sqlite \
    sqlite-dev \
    sqlite-libs \
    sshfs \
    ssl_client \
    subversion \
    subversion-libs \
    tree \
    tzdata \
    wget \
    wireshark-common \
    x11vnc \
    xterm \
    xvfb \
    xz-libs \
    yaml \
    yaml-dev \
    yersinia \
    zlib \
    zlib-dev --allow-untrusted && 
clear && \

# Changing Directory to PIP
cd ../PIP && \

# Running PIP-PIPX-PIPENV Script
sh PIP-PIPX-PIPENV
