#!/bin/ash
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me

printf "Updating, Upgrading, Removing Old APKs, & Cleaning Cache\n" && \
fi

# Updating iSH
apk update && \
clear && \

# Upgrading iSH
apk upgrade && \
clear && \

#Removing  Unneccesary APKs
apk autremove && apk cache && \
clear && \

# Installs necessary files when installed by itself
apk add wget curl bash && \
clear && \

#!/bin/bash
#
printf "Entering into Bash Env. Adding VNC & its' dependencies...\n" && \
fi
#
# Installs x11VNC, xTerm, and Xvfb
apk add x11vnc && \
clear && \
apk add xvfb xvfb-run && \
clear && \
apk add xterm && \
clear && \
#
# Starts Background Daemon
# Allows Persistent Connections, 
# Even When iSH.app is Not Open  
#
ln -s /dev $(dirname $0)/dev
printf "Select 'Always allow'."
cat $(dirname $0)/dev/location > $(dirname $0)/dev/null & #!
#
# Select "While Using App"
# Select "Always"  
#
# Starts x11 VNC Server 
x11vnc -create -noshm -forever && \
#
# Set A Password to Connect:
# x11vnc -rfbauth ~/.vnc/passwd
# Use Your Own VNC Passwd File 
# x11vnc -rfbauth /PATH/file
# Disable Password Usage -nopw 
#
# To Use x11VNC SSL Tunneling 
# '-ssl -stunnel'
# Documentation for x11VNC-SSH Tunneling: 
# http://www.karlrunge.com/x11vnc/#tunnelling   
#
x11vnc -rfbauth -usepw -ssl -stunnel "~/.vnc/passwd" &
#
printf "To Open VNC Viewer on iOS, open VNC Viewer and Use:" && \
printf "127.0.0.1:5900, 0.0.0.0:5900, localhost:0" && \
printf "To view within shortcuts or within a browser," && \
printf "Open safari, add 'VNC://' as a prefix:" && \
printf "VNC://127.0.0.1:5900, VNC://0.0.0.0:5900, VNC://localhost" && \
fi
clear && \

# Changing Directory to APK
cd ../APK && \

# Running APK Installation Scripts
sh APK1
