#!/bin/bash
#
# Creator: I  Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me

alias VNC='vncserver start' && \
alias SSH='ssh weare@192.168.1.3 -p 22' && \
alias etc='cd /etc' && \
alias sys='cd /sys' && \
alias list='ls -trash' && \
alias bin='cd /bin' && \
alias sources='nano /etc/apk/repositories' && \
alias mountdir='mount -t ios . /' && \
alias push='git push' && \
alias pull='git pull' && \
alias fetch='git fetch' && \
alias commit='git commit' && \ 
alias add='git add * ' && \
alias init='git init' && \
alias cheat='sh /usr/local/bin/cht' && \
alias kali='neofetch --ascii_distro kali_small -L' && \
alias ubuntu="neofetch --ascii_distro ubuntu_small -L" && \
alias Install='apk add' && \
alias fix='apk fix' && \
alias update='apk update' && \
alias upgrade='apk upgrade' && \
alias cache='apk cache' && \
alias push='git push' && \
alias fetch='fetch' && \
alias copy='copy' && \
alias add='add' && \
alias commit='git commit' && \
alias pull='git pull' && \
alias delete='rm -r' && \
alias profile='git config --global user.email "projectzerodays@gmail.com" && git config --global user.name "projectzerodays"' && \
clear && \

# Changing Directory to TOOLS
cd TOOLS && \

# Running SSH Setup Script
sh SSH
