#!/bin/ash

# License: GNU public
# Creator: Project Zero Days
# Github:  https://Github.com/ProjectZeroDays
# Website: https://ProjectZeroDays.com
# Email:   Info@ProjectZeroDays.com
# Secure:  ProjectZeroDays@pm.me
# Twitter: @ProjectZeroDays
# Reddit:  @ProjectZeroDays
# DEV:     @ProjectZeroDays 

#Change Directory to SYS/
cd SYS/ && \

echo " The Quieter You Become, 
        The More You Are Able to Hear...
        
        ......,;:ccc,.                              
     ...........''';lxO.                            
.....................,:ld;                        
                     ..debian..                                      
                   root@kali:# who
                 OMo              am
                dMc                 I 
                0M.                           
                ;Wd                                
                 ;4O,
                   0Odc,
                     `::31.,
                        `:;``..
                          'd,  `.
                           ;l    '
                           .o     '
                           c      `
                         .' 
                     . ‘
" >>/etc/motd

# SYS Files to /etc 
cp -f profile /etc/profile && \
cp -f passwd /etc/passwd && \
clear && \

# Making Make-Exec Executable 
chmod +x Make-Exec && \

# Running MAKE-EXEC Script
sh MAKE-EXEC 
