#!/bin/bash
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
#
PS1="root@kali:~# " && \
# Adds More APKs
apk update && \
apk upgrade && \
apk add && 
    libdnet \
    libedit \
    libffi \
    libffi-dev\
    libgcc \
    libgcrypt \
    libgmpxx \
    libgomp \
    libgpg-error \
    libhistory \
    libintl \
    libldap \
    libmagic \
    libmnl \
    libmount \
    libpcap \
    libpcap-dev \
    libpq \
    libressl-dev \
    libressl2.7-libcrypto \
    libressl2.7-libssl \
    libressl2.7-libtls \
    libsasl \
    libssh2 \
    libssl1.1 \
    libstdc++ --allow-untrusted && 
clear && \
sh Apk/Add-Apks4
