#!bin/bash 
#
# Creator: Project Zero Days
# Email:   info@ProjectZeroDays.com
# Github:  Github.com/ProjectZeroDays
# Twitter: Twitter.com/ProjectZeroDays
# Web:     https://ProjectZeroDays.com
# Secure:  https://ProjectZeroDays@pm.me
#
# Adds More APKs
apk update && \
apk upgrade && \
apk add && 
    openssl \
    openssl-dev \
    p11-kit \
    pciutils \
    pciutils-libs \
    pcre \
    pcre2 \
    perl \
    perl-error \
    perl-git \
    php7 \
    php7-common \
    pkgconf \
    postgresql \
    postgresql-client \
    postgresql-dev \
    postgresql-libs \
    proftpd \
    py-pip \
    python2 --allow-untrusted && 
clear && \
sh Apk/Add-Apks6
